version = 1

test_patterns = [
    "*tests/**",
    "*/__tests__/**"
]

exclude_patterns = ["migrations/**"]

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    "Dockerfile"
  ]

  trusted_registries = [
    "registry.hub.docker.com"
  ]

[[analyzers]]
name = "python"
enabled = true
dependency_file_paths = [
  "Pipfile"
]
