version: "3.7"

services:
  server:
    container_name: server
    image: server:development
    env_file:
      - .env
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app
    build:
      context: .
      dockerfile: Dockerfile
